// about page
import Head from 'next/head';
import Nav from '@/components/nav/Nav';
import Mission from '@/components/misc/Mission';
import Footer from '@/components/misc/Footer';

// metadata
export const metadata = {
  title: 'dakota realtors | about page',
  description: 'nextjs real estate app',
};

function About() {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" href="%PUBLIC_URL%/logo192.png" />
      </Head>
      <div className="layout">
        <Nav />
        <div className="about mt-3">
          <div className="containter text-center py-5">
            <h1 className="display-3 py-3">Our Mission</h1>
            <p className="display-6 text-white">
              Helping people find their dream home.
            </p>
          </div>
        </div>
        <div className="container py-5 my-5 ">
          <h2 className="text-center fw-bold py-5 display-3">About</h2>
          <hr className="hr text-center" />
          <Mission />
          <Footer />
        </div>
      </div>
    </>
  );
}

export default About;
