// home model
const mongoose = require('mongoose');

const homeSchema = new mongoose.Schema({
  id: Number,
  mlsId: String,
  name: String,
  photo: String,
  title: String,
  phone: String,
  email: String,
  bio: String,
  experience: String,
  realtor: String,
  propertyType: String,
  rentOrBuy: String,
  verified: String,
  image: String,
  image1: String,
  image2: String,
  image3: String,
  image4: String,
  image5: String,
  description: String,
  rooms: String,
  bathrooms: String,
  centralAir: String,
  washerAndDryer: String,
  dishwasher: String,
  microwave: String,
  flooring: String,
  price: String,
  morgage: String,
  sqft: Number,
  location: String,
  address: String,
  avalibleUnits: Number,
  yearBuilt: Number,
  garageCapacity: String,
  swimmingPool: String,
  swimmingPoolSize: String,
  basement: String,
  fireplace: String,
  school: String,
  college: String,
  communityCenter: String,
  rating: Number,
  numReviews: Number,
  times: String,
  appointments: String,
  slot: String,
  slot2: String,
  slot3: String,
  slot4: String,
  slot5: String,
  slot6: String,
  slot7: String,
  days: String,
});

const Home = mongoose.model('Home', homeSchema);

module.exports = Home;
